In [1]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("files.csv")

In [2]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

               Data Type   Count Unique Values  Missing Values
ts               float64  209237        209191               0
fuid              object  209237        209232               0
tx_hosts          object  209237         15315               0
rx_hosts          object  209237           788               0
conn_uids         object  209237         87997               0
source            object  209237             1               0
depth              int64  209237             1               0
analyzers         object  209237             3               0
mime_type         object  209228            39               9
filename          object   10756          6832          198481
duration         float64  209237         52782               0
local_orig       float64       0             0          209237
is_orig           object  209237             2               0
seen_bytes         int64  209237         39262               0
total_bytes      float64  151095         32104           58142
missing_bytes      int64  209237            81               0
overflow_bytes     int64  209237             1               0
timedout          object  209237             2               0
parent_fuid      float64       0             0          209237
md5               object  209089        125089             148
sha1              object  209089        125089             148
sha256           float64       0             0          209237
extracted        float64       0             0          209237