In [3]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("http.csv",low_memory=False)

In [4]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

                  Data Type   Count Unique Values  Missing Values
ts                  float64  245708        245698               0
uid                  object  245708        103927               0
id.orig_h            object  245708           128               0
id.orig_p             int64  245708          2400               0
id.resp_h            object  245708         16653               0
id.resp_p             int64  245708            80               0
trans_depth           int64  245708           307               0
method               object  245686             7              22
host                 object  243129         15681            2579
uri                  object  245686        137398              22
referrer             object  202232         14350           43476
user_agent           object  244201           263            1507
request_body_len      int64  245708           518               0
response_body_len     int64  245708         39244               0
status_code         float64  242791            23            2917
status_msg           object  242791            79            2917
info_code           float64       8             1          245700
info_msg             object       8             1          245700
filename            float64       0             0          245708
tags                 object  245708             2               0
username             object       1             1          245707
password            float64       0             0          245708
proxied              object       6             1          245702
orig_fuids           object    2960          2960          242748
orig_mime_types      object    2960            10          242748
resp_fuids           object  206251        206247           39457
resp_mime_types      object  206251            41           39457