In [1]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("irc.csv")

In [2]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

              Data Type  Count Unique Values  Missing Values
ts              float64     21            15               0
uid              object     21             6               0
id.orig_h        object     21             6               0
id.orig_p         int64     21             6               0
id.resp_h        object     21             5               0
id.resp_p         int64     21             5               0
nick             object     15             6               6
user             object      9             6              12
command          object     21             3               0
value            object     21            18               0
addl             object     15            12               6
dcc_file_name   float64      0             0              21
dcc_file_size   float64      0             0              21
dcc_mime_type   float64      0             0              21
fuid            float64      0             0              21