In [1]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("conn.csv")

In [2]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

               Data Type   Count Unique Values  Missing Values
ts               float64  130331        130331               0
uid               object  130331        130331               0
id.orig_h         object  130331           631               0
id.orig_p          int64  130331          3990               0
id.resp_h         object  130331         23057               0
id.resp_p          int64  130331           221               0
proto             object  130331             3               0
service           object   84232             7           46099
duration         float64  109369        104147           20962
orig_bytes       float64  109369          5830           20962
resp_bytes       float64  109369         24375           20962
conn_state        object  130331            13               0
local_orig       float64       0             0          130331
missed_bytes       int64  130331            81               0
history           object  129509           211             822
orig_pkts          int64  130331           864               0
orig_ip_bytes      int64  130331          9340               0
resp_pkts          int64  130331          1161               0
resp_ip_bytes      int64  130331         25977               0
tunnel_parents    object  130331             1               0