In [1]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("notice.csv")

In [2]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

               Data Type  Count Unique Values  Missing Values
ts               float64    387             8             295
uid              float64      0             0             682
id.orig_h        float64      0             0             682
id.orig_p        float64      0             0             682
id.resp_h         object    495             1             187
id.resp_p         object    682             7               0
fuid              object    682           215               0
file_mime_type    object    660            41              22
file_desc         object    682            64               0
proto             object    534           105             148
note             float64    495            25             187
msg              float64      0             0             682
sub               object    682             1               0
src               object    682             1               0
dst              float64    682             1               0
p                 object    682             1               0
n                float64      0             0             682
peer_descr       float64      0             0             682
actions          float64      0             0             682
suppress_for     float64      0             0             682
dropped          float64      0             0             682