In [1]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("ftp.csv")

In [2]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

                     Data Type  Count Unique Values  Missing Values
ts                     float64     24            24               0
uid                     object     24             7               0
id.orig_h               object     24             2               0
id.orig_p                int64     24             7               0
id.resp_h               object     24             1               0
id.resp_p                int64     24             1               0
user                    object     24             1               0
password                object     24             1               0
command                 object     24             4               0
arg                     object     16             8               8
mime_type               object      2             1              22
file_size              float64      2             2              22
reply_code               int64     24             4               0
reply_msg               object     24            11               0
data_channel.passive    object     14             2              10
data_channel.orig_h     object     14             3              10
data_channel.resp_h     object     14             2              10
data_channel.resp_p    float64     14            11              10
fuid                    object      2             2              22