In [5]:
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("dpd.csv")

In [6]:
#DataFrame with columns
columns = pd.DataFrame(list(df.columns.values[1:]))

#DataFrame with data types
data_types = pd.DataFrame(df.dtypes, columns=['Data Type'])

#DataFrame with Count
data_count = pd.DataFrame(df.count(), columns=['Count'])

#DataFrame with unique values
unique_value_counts = pd.DataFrame(columns=['Unique Values'])
for v in list(df.columns.values):
    unique_value_counts.loc[v] = [df[v].nunique()]

missing_data_counts = pd.DataFrame(df.isnull().sum(), columns=['Missing Values'])
data_quality_report = data_types.join(data_count).join(unique_value_counts).join(missing_data_counts)
print('Data Quality Report')
data_quality_report

Data Quality Report

               Data Type  Count Unique Values  Missing Values
ts               float64     88            88               0
uid               object     88            88               0
id.orig_h         object     88            31               0
id.orig_p          int64     88            65               0
id.resp_h         object     88            30               0
id.resp_p          int64     88             6               0
proto             object     88             1               0
analyzer          object     88             2               0
failure_reason    object     88             4               0